package nl.kmartin.knitster.theme.color

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val CreamLightScheme = lightColorScheme(
    primary = Color(0xFF7B580D),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDEAA),
    onPrimaryContainer = Color(0xFF5F4100),
    secondary = Color(0xFF6D5C3F),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF8DFBB),
    onSecondaryContainer = Color(0xFF54442A),
    tertiary = Color(0xFF4D6543),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFCFEBC0),
    onTertiaryContainer = Color(0xFF364D2D),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFFFF8F3),
    onBackground = Color(0xFF201B13),
    surface = Color(0xFFFFF8F3),
    onSurface = Color(0xFF201B13),
    surfaceVariant = Color(0xFFEEE0CF),
    onSurfaceVariant = Color(0xFF4E4639),
    outline = Color(0xFF807667),
    outlineVariant = Color(0xFFD2C5B4),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF353027),
    inverseOnSurface = Color(0xFFFAEFE2),
    inversePrimary = Color(0xFFEEBF6D),
    surfaceDim = Color(0xFFE3D8CC),
    surfaceBright = Color(0xFFFFF8F3),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFDF2E5),
    surfaceContainer = Color(0xFFF8ECDF),
    surfaceContainerHigh = Color(0xFFF2E6D9),
    surfaceContainerHighest = Color(0xFFECE1D4),
)

val CreamDarkScheme = darkColorScheme(
    primary = Color(0xFFEEBF6D),
    onPrimary = Color(0xFF422C00),
    primaryContainer = Color(0xFF5F4100),
    onPrimaryContainer = Color(0xFFFFDEAA),
    secondary = Color(0xFFDAC3A1),
    onSecondary = Color(0xFF3C2E16),
    secondaryContainer = Color(0xFF54442A),
    onSecondaryContainer = Color(0xFFF8DFBB),
    tertiary = Color(0xFFB4CEA5),
    onTertiary = Color(0xFF203619),
    tertiaryContainer = Color(0xFF364D2D),
    onTertiaryContainer = Color(0xFFCFEBC0),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF17130B),
    onBackground = Color(0xFFECE1D4),
    surface = Color(0xFF17130B),
    onSurface = Color(0xFFECE1D4),
    surfaceVariant = Color(0xFF4E4639),
    onSurfaceVariant = Color(0xFFD2C5B4),
    outline = Color(0xFF9A8F80),
    outlineVariant = Color(0xFF4E4639),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFECE1D4),
    inverseOnSurface = Color(0xFF353027),
    inversePrimary = Color(0xFF7B580D),
    surfaceDim = Color(0xFF17130B),
    surfaceBright = Color(0xFF3E382F),
    surfaceContainerLowest = Color(0xFF120E07),
    surfaceContainerLow = Color(0xFF201B13),
    surfaceContainer = Color(0xFF241F17),
    surfaceContainerHigh = Color(0xFF2F2921),
    surfaceContainerHighest = Color(0xFF3A342B),
)
