package nl.kmartin.knitster.theme.color

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Theme generated using Material Theme Builder
 */
val CreamLightScheme = lightColorScheme(
    primary = Color(0xFF625E51),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFF8E7),
    onPrimaryContainer = Color(0xFF767264),
    secondary = Color(0xFF615E58),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE4DFD7),
    onSecondaryContainer = Color(0xFF65625C),
    tertiary = Color(0xFF5D6054),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFF8FAEB),
    onTertiaryContainer = Color(0xFF707367),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFFDF8F6),
    onBackground = Color(0xFF1C1B1A),
    surface = Color(0xFFFDF8F6),
    onSurface = Color(0xFF1C1B1A),
    surfaceVariant = Color(0xFFE8E2D7),
    onSurfaceVariant = Color(0xFF49473F),
    outline = Color(0xFF7A776E),
    outlineVariant = Color(0xFFCBC6BB),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF31302F),
    inverseOnSurface = Color(0xFFF4F0ED),
    inversePrimary = Color(0xFFCCC6B6),
    surfaceDim = Color(0xFFDDD9D7),
    surfaceBright = Color(0xFFFDF8F6),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF7F3F0),
    surfaceContainer = Color(0xFFF1EDEB),
    surfaceContainerHigh = Color(0xFFECE7E5),
    surfaceContainerHighest = Color(0xFFE6E2DF),
)

val CreamDarkScheme = darkColorScheme(
    primary = Color(0xFFFFFFFF),
    onPrimary = Color(0xFF333025),
    primaryContainer = Color(0xFFE9E2D2),
    onPrimaryContainer = Color(0xFF686457),
    secondary = Color(0xFFCBC6BE),
    onSecondary = Color(0xFF32302B),
    secondaryContainer = Color(0xFF494741),
    onSecondaryContainer = Color(0xFFB9B5AD),
    tertiary = Color(0xFFFFFFFF),
    onTertiary = Color(0xFF2E3228),
    tertiaryContainer = Color(0xFFE2E4D5),
    onTertiaryContainer = Color(0xFF63665A),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF141312),
    onBackground = Color(0xFFE6E2DF),
    surface = Color(0xFF141312),
    onSurface = Color(0xFFE6E2DF),
    surfaceVariant = Color(0xFF49473F),
    onSurfaceVariant = Color(0xFFCBC6BB),
    outline = Color(0xFF949087),
    outlineVariant = Color(0xFF49473F),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE6E2DF),
    inverseOnSurface = Color(0xFF31302F),
    inversePrimary = Color(0xFF625E51),
    surfaceDim = Color(0xFF141312),
    surfaceBright = Color(0xFF3A3938),
    surfaceContainerLowest = Color(0xFF0F0E0D),
    surfaceContainerLow = Color(0xFF1C1B1A),
    surfaceContainer = Color(0xFF201F1E),
    surfaceContainerHigh = Color(0xFF2B2A28),
    surfaceContainerHighest = Color(0xFF363433),
)