package nl.kmartin.knitster.theme.color

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Theme generated using Material Theme Builder
 */
val GreenLightScheme = lightColorScheme(
    primary = Color(0xFF416835),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFC1EFAF),
    onPrimaryContainer = Color(0xFF294F1F),
    secondary = Color(0xFF54634D),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD7E8CC),
    onSecondaryContainer = Color(0xFF3D4B37),
    tertiary = Color(0xFF386668),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFBCEBEE),
    onTertiaryContainer = Color(0xFF1E4E50),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFF8FBF0),
    onBackground = Color(0xFF191D17),
    surface = Color(0xFFF8FBF0),
    onSurface = Color(0xFF191D17),
    surfaceVariant = Color(0xFFDFE4D7),
    onSurfaceVariant = Color(0xFF43483F),
    outline = Color(0xFF73796E),
    outlineVariant = Color(0xFFC3C8BC),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF2E322B),
    inverseOnSurface = Color(0xFFEFF2E8),
    inversePrimary = Color(0xFFA6D395),
    surfaceDim = Color(0xFFD8DBD2),
    surfaceBright = Color(0xFFF8FBF0),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF2F5EB),
    surfaceContainer = Color(0xFFECEFE5),
    surfaceContainerHigh = Color(0xFFE6E9DF),
    surfaceContainerHighest = Color(0xFFE1E4DA),
)

val GreenDarkScheme = darkColorScheme(
    primary = Color(0xFFA6D395),
    onPrimary = Color(0xFF12380A),
    primaryContainer = Color(0xFF294F1F),
    onPrimaryContainer = Color(0xFFC1EFAF),
    secondary = Color(0xFFBBCBB1),
    onSecondary = Color(0xFF273422),
    secondaryContainer = Color(0xFF3D4B37),
    onSecondaryContainer = Color(0xFFD7E8CC),
    tertiary = Color(0xFFA0CFD1),
    onTertiary = Color(0xFF003739),
    tertiaryContainer = Color(0xFF1E4E50),
    onTertiaryContainer = Color(0xFFBCEBEE),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF11140F),
    onBackground = Color(0xFFE1E4DA),
    surface = Color(0xFF11140F),
    onSurface = Color(0xFFE1E4DA),
    surfaceVariant = Color(0xFF43483F),
    onSurfaceVariant = Color(0xFFC3C8BC),
    outline = Color(0xFF8D9387),
    outlineVariant = Color(0xFF43483F),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE1E4DA),
    inverseOnSurface = Color(0xFF2E322B),
    inversePrimary = Color(0xFF416835),
    surfaceDim = Color(0xFF11140F),
    surfaceBright = Color(0xFF373A34),
    surfaceContainerLowest = Color(0xFF0C0F0A),
    surfaceContainerLow = Color(0xFF191D17),
    surfaceContainer = Color(0xFF1D211B),
    surfaceContainerHigh = Color(0xFF272B25),
    surfaceContainerHighest = Color(0xFF32362F),
)