package nl.kmartin.knitster.theme.color

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val PinkLightScheme = lightColorScheme(
    primary = Color(0xFF864B6E),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD8EA),
    onPrimaryContainer = Color(0xFF6B3456),
    secondary = Color(0xFF715764),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFCD9E9),
    onSecondaryContainer = Color(0xFF58404C),
    tertiary = Color(0xFF80543C),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDBCA),
    onTertiaryContainer = Color(0xFF653D27),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFFFF8F8),
    onBackground = Color(0xFF211A1D),
    surface = Color(0xFFFFF8F8),
    onSurface = Color(0xFF211A1D),
    surfaceVariant = Color(0xFFF0DEE5),
    onSurfaceVariant = Color(0xFF504349),
    outline = Color(0xFF827379),
    outlineVariant = Color(0xFFD3C2C9),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF362E32),
    inverseOnSurface = Color(0xFFFCEDF2),
    inversePrimary = Color(0xFFFAB1D9),
    surfaceDim = Color(0xFFE5D6DB),
    surfaceBright = Color(0xFFFFF8F8),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFFF0F5),
    surfaceContainer = Color(0xFFF9EAEF),
    surfaceContainerHigh = Color(0xFFF3E4E9),
    surfaceContainerHighest = Color(0xFFEDDFE4),
)

val PinkDarkScheme = darkColorScheme(
    primary = Color(0xFFFAB1D9),
    onPrimary = Color(0xFF511D3E),
    primaryContainer = Color(0xFF6B3456),
    onPrimaryContainer = Color(0xFFFFD8EA),
    secondary = Color(0xFFDFBECD),
    onSecondary = Color(0xFF402A36),
    secondaryContainer = Color(0xFF58404C),
    onSecondaryContainer = Color(0xFFFCD9E9),
    tertiary = Color(0xFFF3BA9D),
    onTertiary = Color(0xFF4A2713),
    tertiaryContainer = Color(0xFF653D27),
    onTertiaryContainer = Color(0xFFFFDBCA),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF181115),
    onBackground = Color(0xFFEDDFE4),
    surface = Color(0xFF181115),
    onSurface = Color(0xFFEDDFE4),
    surfaceVariant = Color(0xFF504349),
    onSurfaceVariant = Color(0xFFD3C2C9),
    outline = Color(0xFF9C8D93),
    outlineVariant = Color(0xFF504349),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFEDDFE4),
    inverseOnSurface = Color(0xFF362E32),
    inversePrimary = Color(0xFF864B6E),
    surfaceDim = Color(0xFF181115),
    surfaceBright = Color(0xFF3F373B),
    surfaceContainerLowest = Color(0xFF130C10),
    surfaceContainerLow = Color(0xFF211A1D),
    surfaceContainer = Color(0xFF251E21),
    surfaceContainerHigh = Color(0xFF30282B),
    surfaceContainerHighest = Color(0xFF3B3236),
)